MySocialLoginTrial/MySocialLoginService/Models/ErrorViewModel.cs
using System;

namespace MySocialLoginService.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MySocialLoginTrial/MySocialLoginService/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySocialLoginService.Models;

namespace MySocialLoginService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MySocialLoginTrial/MySocialLoginService/Pages/SocialLogin/MExternalLogins.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace MySocialLoginService.Pages.SocialLogin
{

    [IgnoreAntiforgeryToken]
    public class MyExternalLoginsModel : PageModel
    {
        private const string USE_ID = "MyExternalLogin_UserID";
        private const string RETURN_URL = "MyExternalLogin_ReturnUrl";

        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public MyExternalLoginsModel(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IList<UserLoginInfo> CurrentLogins { get; set; }

        public IList<AuthenticationScheme> OtherLogins { get; set; }

        [TempData]
        public string StatusMessage { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            OtherLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync())
                .ToList();
            return Page();
        }

        public async Task<IActionResult> OnPostLinkLoginAsync(string provider, string userId = null, string returnUrl = null)
        {
            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            // Put argument userId and returnUrl into Session.
            if (string.IsNullOrEmpty(userId))
            {
                userId = "(not set)";
            }

            if (!string.IsNullOrEmpty(returnUrl))
            {
                returnUrl = WebUtility.UrlDecode(returnUrl);
            }
            else
            {
                returnUrl = "(not set)";
            }
            HttpContext.Session.SetString(USE_ID, userId);
            HttpContext.Session.SetString(RETURN_URL,returnUrl);

            // Request a redirect to the external login provider to link a login for the current user
            var redirectUrl = Url.Page("/SocialLogin/MyExternalLogins", pageHandler: "LinkLoginCallback");
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl, userId);

            return new ChallengeResult(provider, properties);
        }

        public async Task<IActionResult> OnGetLinkLoginCallbackAsync()
        {
            // pull urseId and returnUrl from Session and remove them.
            var userId = HttpContext.Session.GetString(USE_ID);
            var returnUrl = HttpContext.Session.GetString(RETURN_URL);
            HttpContext.Session.Remove(USE_ID);
            HttpContext.Session.Remove(RETURN_URL);

            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                throw new InvalidOperationException($"Unexpected error occurred loading external login info.");
            }

            var mailaddress = string.Empty;
            try
            {
                // どうやらOAuthの規約で認証時のユーザー情報はIdentityでは標準的にここに入ってくるらしい。
                mailaddress = info.Principal.Claims.First().Subject.Claims.Where(c => c.Type.Contains("/identity/claims/emailaddress")).First().Value;
            }
            catch (Exception exp)
            {
                mailaddress = "(could not get because ... " + exp.Message + ")";
            }

            var message = string.Format("Social Account for ProviderID: {0} and ProviderKey: {1} and EMailAddress: {2} will bind to " +
                "Sight memeber with UserId: {3}, then redirect to {4}. " +
                "(This part is not implemented in this program.)",
                info.LoginProvider, info.ProviderKey, mailaddress, userId, returnUrl); ;
            StatusMessage = message;

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            return RedirectToPage();
        }
    }
}

MySocialLoginTrial/MySocialLoginService/Pages/SocialLogin/MyExternalLogins.cshtml
@page
@model MySocialLoginService.Pages.SocialLogin.MyExternalLoginsModel
@{
    ViewData["Title"] = "Manage your external logins";
}

<partial name="_StatusMessage" for="StatusMessage" />
@if (Model.CurrentLogins?.Count > 0)
{
    <h4>Registered Logins</h4>
    <table class="table">
        <tbody>
            @foreach (var login in Model.CurrentLogins)
            {
                <tr>
                    <td id="@($"login-provider-{login.LoginProvider}")">@login.ProviderDisplayName</td>
                </tr>
            }
        </tbody>
    </table>
}
@if (Model.OtherLogins?.Count > 0)
{
    <h4>Add another service to log in.</h4>
    <hr />
    <form id="link-login-form" asp-page-handler="LinkLogin" method="post" class="form-horizontal">
        <div id="socialLoginList">
            <p>
                @foreach (var provider in Model.OtherLogins)
                {
                    <button id="@($"link-login-button-{provider.Name}")" type="submit" class="btn btn-primary" name="provider" value="@provider.Name" title="Log in using your @provider.DisplayName account">@provider.DisplayName</button>
                }
            </p>
        </div>
    </form>
}

MySocialLoginTrial/MySocialLoginService/Pages/SocialLogin/_Layout.cshtml
@{
    if (ViewData.TryGetValue("ParentLayout", out var parentLayout))
    {
        Layout = (string)parentLayout;
    }
    else
    {
        Layout = "/Areas/Identity/Pages/_Layout.cshtml";
    }
}

<h2>Manage your account</h2>

<div>
    <h4>Change your account settings</h4>
    <hr />
    <div class="row">
        <div class="col-md-3">
            <partial name="_ManageNav" />
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

@section Scripts {
    @RenderSection("Scripts", required: false)
}

MySocialLoginTrial/MySocialLoginService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MySocialLoginService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MySocialLoginService</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="~/SocialLogin/MyExternalLogins">MyExternalLogins</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MySocialLoginService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>